apiVersion: v2
name: website
description: A Helm chart for website deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - website
  - frontend
maintainers:
  - name: Your Name
    email: you@example.com
